development:
  adapter: postgresql
  encoding: unicode
  database: acaplans_development
  pool: 5
  username: acaplans
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: acaplans_test
  pool: 5
  username: acaplans
  password:
